class Contact {
  String name, id, phone;
  String email;
  dynamic dob,payment_term;
  String? customer_id,
      profile,
      bio,
      gender,
      address,
      facebook,
      linkedin,
      region_id,
      report_to,
      position_of_report_to,
      priority,
      tags_id,
      emp_id,
      department,
      position,
      status,
      lead_title,
      customer_type,
      credit_limit,
      current_credit,
      advance_balance,
      branch_id,
      zone_id,
      main_customer,
      use_amount,
      
      sales_type,
      shop_name,
      company_id,
      item_id,
      existing_business,
      segment,
      interest_level;

  Contact(
      {required this.name,
      required this.id,
      required this.email,
      required this.phone,
      required this.profile,
      required this.bio,
      required this.gender,
      required this.address,
      required this.facebook,
      required this.linkedin,
      required this.region_id,
      required this.report_to,
      required this.position_of_report_to,
      required this.priority,
      required this.tags_id,
      required this.emp_id,
      required this.department,
      required this.position,
      required this.status,
      required this.lead_title,
      required this.customer_type,
      required this.credit_limit,
      required this.current_credit,
      required this.advance_balance,
      required this.branch_id,
      required this.zone_id,
      required this.main_customer,
      required this.use_amount,
      required this.payment_term,
      required this.sales_type,
      required this.shop_name,
      required this.company_id,
      required this.item_id,
      required this.existing_business,
      required this.segment,
      required this.interest_level,
      required this.dob,
      required this.customer_id});
  factory Contact.fromJson(dynamic json) {
    return Contact(
        customer_id: json['customer_id'],
        name: json['name'],
        id: json['id'].toString(),
        email: json['email'],
        phone: json['phone'],
        profile: json['profile'],
        bio: json['bio'],
        gender: json['gender'],
        address: json['address']??'N/A',
        facebook: json['facebook'],
        linkedin: json['linkedin'],
        region_id: json['region_id'].toString(),
        report_to: json['report_to'],
        position_of_report_to: json['position_of_report_to'],
        priority: json['priority'],
        tags_id: json['tag_id'].toString(),
        emp_id: json['emp_id'].toString(),
        department: json['department'],
        position: json['position'],
        status: json['status'],
        lead_title: json['lead_title'],
        customer_type: json['customer_type'],
        credit_limit: json['credit_limit'].toString(),
        current_credit: json['current_credit'].toString(),
        advance_balance: json['advance_balance'].toString(),
        branch_id: json['branch_id'].toString(),
        zone_id: json['zone_id'].toString(),
        main_customer: json['main_customer'].toString(),
        use_amount: json['use_amount'].toString(),
        payment_term: json['payment_term'],
        sales_type: json['sales_type'],
        shop_name: json['shop_name'],
        company_id: json['company_id'].toString(),
        item_id: json['item_id'].toString(),
        existing_business: json['exitsting_business'],
        segment: json['segment'],
        interest_level: json['interest_level'],
        dob: json['dob']);
  }
}

